//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int idProduto { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public decimal preco { get; set; }
        public int idCategoria { get; set; }
        public int quantidade { get; set; }
        public string foto { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<bool> promo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
