//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public string numero { get; set; }
        public System.DateTime validade { get; set; }
        public string nomeCartao { get; set; }
        public string codigo { get; set; }
        public string bandeira { get; set; }
        public int idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
