//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaDesejo
    {
        public int idLista { get; set; }
        public int idProduto { get; set; }
        public int idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
