//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int idPedido { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public int idCliente { get; set; }
        public string formaPagamento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ItemPedido ItemPedido { get; set; }
    }
}
